# Generated by Django 2.2.1 on 2019-05-26 13:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('subcategory', models.CharField(max_length=200)),
                ('duration', models.IntegerField()),
                ('experiance_level', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('paid_unpaid', models.CharField(max_length=200)),
                ('list_date', models.DateField(blank=True, default=datetime.datetime.now)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clients.Client')),
            ],
        ),
    ]
