# Generated by Django 2.2.1 on 2019-06-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stupro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.IntegerField()),
                ('nick_name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('skills', models.TextField(blank=True)),
                ('project', models.CharField(max_length=100)),
                ('collegename', models.CharField(max_length=100)),
            ],
        ),
    ]
