# Generated by Django 2.2.1 on 2019-06-30 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20190629_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='firstname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='lastname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
