# Generated by Django 2.2.1 on 2019-06-30 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20190630_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
