# Generated by Django 2.2.1 on 2019-07-06 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_remove_client_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='client',
            name='hire_date',
        ),
        migrations.RemoveField(
            model_name='client',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='client',
            name='password',
        ),
    ]
