# Generated by Django 2.2.1 on 2019-07-06 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_auto_20190706_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_id',
            field=models.IntegerField(null=True),
        ),
    ]
