# Generated by Django 2.2.1 on 2019-08-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_client_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='about_company',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
