# Generated by Django 2.2.1 on 2019-08-21 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_postjob_c_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postjob',
            name='c_id',
        ),
    ]
