# Generated by Django 2.2.1 on 2019-08-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_remove_postjob_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='postjob',
            name='Id_client',
            field=models.IntegerField(null=True),
        ),
    ]
