# Generated by Django 2.2.1 on 2019-08-21 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_postjob_id_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='postjob',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clients.Client'),
        ),
    ]
